### ISSUE TITLE
Scroom in Windows

### ISSUE THREAD

**Issue by eugenschindler** [kees-jan/scroom#47]
I know that this may not be perceived as an issue, but: I was wondering what environment best to use in order to build a scroom executable for Windows.

**Comment by kees-jan** [comment]
I don't know exactly. This is still on my todo list to figure out once. If I remember correctly, @rcaelers recommends either using msys on windows, or cross compiling. Workrave is doing this, but I have not yet taken the time to figure out how exactly.

**Comment by kees-jan** [comment]
The next release should have a windows version. Until then, try one of the [development snapshots](https://fuzzy.mandryn.eu/~project/scroom/travis/builds/next/)
