### ISSUE TITLE
Bright lines between tiles visible for certain zoomlevels

### ISSUE THREAD

**Issue by JoostvanPinxten** [kees-jan/scroom#75]
Especially when viewing some larger files, we see some bright lines between the tiles. It seems to depend on the zoomlevel whether these (1px or at most 2px in screen resolution) lines are visible.

![image](https://user-images.githubusercontent.com/3332970/91535847-14743800-e914-11ea-9c06-961f3344333f.png)

Perhaps there is a off-by-one in the rounding introduced by the support for aspect ratios?

This happens on Windows 10, and I haven't tried the Ubuntu version of Scroom. So I don't know whether it reproduces there.

**Comment by kees-jan** [comment]
Ouch. I've seen those before. That might depend on the version of Cairo being used, but it might also be a rounding error. In my experience, they are hard to reproduce. Could you share the file that exposes the problem for you? That might save some searching on my side.

**Comment by JoostvanPinxten** [comment]
Good that you have a starting point to search for. BTW: It is not a very urgent bug, as it does not show up in all zoom levels.

I'll send you an email, because the file size was too large for GitHub, even after zipping...

**Comment by JoostvanPinxten** [comment]
Added some additional info about OS in the bug report.

**Comment by kees-jan** [comment]
With your image, it reproduces on Linux. So not OS or Cairo dependent. Must indeed be a rounding error somewhere.

**Comment by kees-jan** [comment]
The problem I've managed to reproduce is present in the `next` branch, but not in the `0.11` version, which I was assuming you're using.

Can you confirm that you're indeed using scroom `0.11` without any further changes? Because then I have to redo some of my tests.

**Comment by JoostvanPinxten** [comment]
We are indeed not actually using the `0.11` version, but the build of the `next` branch, from the 8th of july. In the About window, this is shown as version 0.11 though.

**Comment by kees-jan** [comment]
Hmm... The About window is usually pretty accurate. If it claims it is 0.11, I tend to believe it. I'll do some more investigating.

**Comment by kees-jan** [comment]
Confirmed the problem in the windows build of 0.11. It indeed appears only sometimes, though resizing the scroom window is a fairly easy way to trigger it.

**Comment by kees-jan** [comment]
[This build](https://fuzzy.mandryn.eu/~project/scroom/travis/scroom-cpp/builds/master/43) (or anything later) should be better
